# Generated by Django 5.2.9 on 2026-02-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_pro_profile_pro_current_period_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
