# Generated by Django 5.2.9 on 2026-01-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmatch',
            options={'ordering': ['-matched_at'], 'verbose_name_plural': 'content matches'},
        ),
    ]
