# Generated by Django 5.2.9 on 2026-01-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
