# Generated by Django 5.2.9 on 2026-01-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsource',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contentsource',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
