# Generated by Django 5.2.9 on 2026-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_contentsource_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
