# Generated by Django 5.2.9 on 2026-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_contentitemsource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='origin_type',
            field=models.CharField(choices=[('periodic', 'Periodic'), ('user', 'User'), ('admin', 'Admin'), ('cli', 'CLI')], default='user', max_length=20),
        ),
    ]
