# Generated by Django 5.2.9 on 2026-01-12 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentitem_keyword_delete_contentmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='origin_type',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentitemsource',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='content.contentitem'),
        ),
        migrations.AlterField(
            model_name='contentitemsource',
            name='content_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='content.contentsource'),
        ),
    ]
