# Generated by Django 5.2.9 on 2026-01-07 12:32

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_fetched_at', '-created_at'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='keyword_embedding_hnsw', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
