# Generated by Django 5.2.9 on 2026-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='status',
        ),
        migrations.AddField(
            model_name='keyword',
            name='normalized_text',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
