# Generated by Django 5.2.9 on 2026-01-14 10:38

import django.core.validators
import newsradar.keywords.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_updated_after_filter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='last_updated_before_filter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='max_results',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='max_tokens',
            field=models.PositiveIntegerField(default=25000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='max_tokens_per_page',
            field=models.PositiveIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='provider',
            field=models.CharField(default='perplexity', max_length=20),
        ),
        migrations.AddField(
            model_name='keyword',
            name='provider_config',
            field=models.JSONField(blank=True, null=True, validators=[newsradar.keywords.models.validate_provider_config]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_after_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_before_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_domain_allowlist',
            field=models.JSONField(blank=True, null=True, validators=[newsradar.keywords.models.validate_domain_filter]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_domain_blocklist',
            field=models.JSONField(blank=True, null=True, validators=[newsradar.keywords.models.validate_domain_filter]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_language_filter',
            field=models.JSONField(blank=True, null=True, validators=[newsradar.keywords.models.validate_language_filter]),
        ),
        migrations.AddField(
            model_name='keyword',
            name='search_recency_filter',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=5, null=True),
        ),
    ]
