# Generated by Django 5.2.9 on 2026-01-14 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_country_keyword_last_updated_after_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
