# Generated by Django 5.2.9 on 2026-01-14 10:40

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Keyword = apps.get_model("keywords", "Keyword")
    for row in Keyword.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_add_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
