# Generated by Django 5.2.9 on 2026-01-14 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
