# Generated by Django 5.2.9 on 2026-01-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_remove_uuid_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='normalized_text',
        ),
        migrations.AddField(
            model_name='keyword',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='provider',
            field=models.CharField(default='openai', max_length=20),
        ),
    ]
