# Generated by Django 5.2.9 on 2026-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_remove_keyword_normalized_text_keyword_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='provider',
            field=models.CharField(default='perplexity', max_length=20),
        ),
    ]
