# Generated by Django 5.2.9 on 2026-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('initiator', models.CharField(choices=[('periodic', 'Periodic'), ('user', 'User'), ('admin', 'Admin'), ('cli', 'CLI')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='topics.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
