# Generated by Django 5.2.9 on 2026-01-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0008_remove_contentitem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('origin_type', models.CharField(choices=[('periodic', 'Periodic'), ('user', 'User'), ('admin', 'Admin'), ('cli', 'CLI')], default='user', max_length=20)),
                ('llm_config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='content.contentitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
