# Generated by Django 5.2.9 on 2026-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='request_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
