# Generated by Django 5.2.9 on 2026-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_purge_legacy_content_schema"),
        ("executions", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS executions_execution CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="Execution",
                ),
            ],
        ),
    ]
