# Generated by Django 5.2.9 on 2026-01-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentitem_updated_at_and_more'),
        ('executions', '0002_execution_error_message_execution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='content_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='content.contentitem'),
        ),
    ]
