# Generated by Django 5.2.9 on 2026-04-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0002_purge_legacy_execution_schema"),
        ("topics", "0002_purge_legacy_topic_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                (
                    "initiator",
                    models.CharField(
                        choices=[
                            ("periodic", "Periodic"),
                            ("user", "User"),
                            ("admin", "Admin"),
                            ("cli", "CLI"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
