# Generated by Django 5.2.9 on 2026-02-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0002_execution_request_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
