# Generated by Django 5.2.9 on 2026-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_bookmark'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_execution_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('execution', 'url', 'last_updated'), name='unique_execution_url'),
        ),
    ]
