# Generated by Django 5.2.9 on 2026-01-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0004_content_snippet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="metadata",
        ),
    ]
