# Generated by Django 5.2.9 on 2026-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_content_metadata'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_execution_url',
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('url', 'date', 'last_updated'), name='unique_content'),
        ),
    ]
