# Generated by Django 5.2.9 on 2026-01-20 12:34

import django.db.models.deletion
from django.db import migrations, models


def populate_content_topic(apps, schema_editor):
    Content = apps.get_model("contents", "Content")

    batch = []
    for content in Content.objects.select_related("execution").iterator(chunk_size=1000):
        if content.topic_id is not None:
            continue
        if content.execution_id is None:
            continue
        content.topic_id = content.execution.topic_id
        batch.append(content)
        if len(batch) >= 1000:
            Content.objects.bulk_update(batch, ["topic"])
            batch = []

    if batch:
        Content.objects.bulk_update(batch, ["topic"])

    if Content.objects.filter(topic__isnull=True).exists():
        raise RuntimeError("Unable to populate content.topic for all rows.")


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0006_remove_content_unique_execution_url_and_more"),
        ("topics", "0007_alter_topicgroup_default_search_language_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_items",
                to="topics.topic",
            ),
        ),
        migrations.RunPython(populate_content_topic, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="content",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_items",
                to="topics.topic",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="content",
            name="unique_content",
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("url", "date", "last_updated", "topic"),
                name="unique_content",
            ),
        ),
    ]
