# Generated by Django 5.2.9 on 2026-02-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content_topic_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('instruction', models.TextField()),
                ('context_content_ids', models.JSONField(default=list)),
                ('context_payload', models.JSONField(default=list)),
                ('model_requested', models.CharField(max_length=120)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('response_id', models.CharField(blank=True, max_length=120)),
                ('response_text', models.TextField(blank=True)),
                ('usage_payload', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('credits_used', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='contents_ai_user_id_d094ee_idx'), models.Index(fields=['status', '-created_at'], name='contents_ai_status_eee813_idx')],
            },
        ),
    ]
