# Generated by Django 5.2.9 on 2026-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_aiinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
