# Generated by Django 5.2.9 on 2026-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0009_content_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="viewed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
