# Generated by Django 5.2.9 on 2026-01-15 10:55

import django.db.models.deletion
import newsradar.topics.models
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('queries', models.JSONField(default=list, validators=[newsradar.topics.models.validate_topic_queries])),
                ('search_domain_allowlist', models.JSONField(blank=True, null=True, validators=[newsradar.topics.models.validate_domain_filter])),
                ('search_domain_blocklist', models.JSONField(blank=True, null=True, validators=[newsradar.topics.models.validate_domain_filter])),
                ('search_language_filter', models.JSONField(blank=True, null=True, validators=[newsradar.topics.models.validate_language_filter])),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('search_recency_filter', models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=5, null=True)),
                ('search_after_date', models.DateField(blank=True, null=True)),
                ('search_before_date', models.DateField(blank=True, null=True)),
                ('last_updated_after_filter', models.DateField(blank=True, null=True)),
                ('last_updated_before_filter', models.DateField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_fetched_at', '-created_at'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='topic_embedding_hnsw', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
