# Generated by Django 5.2.9 on 2026-04-02 00:00

import django.db.models.deletion
import newsradar.topics.models
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("executions", "0002_purge_legacy_execution_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS topics_topic CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS topics_topicgroup CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="Topic",
                ),
                migrations.DeleteModel(
                    name="TopicGroup",
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name"),
                        name="unique_topic_group_name",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("monitoring_prompt", models.TextField(blank=True, default="")),
                ("display_title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("auto", "auto"),
                            ("hour", "hour"),
                            ("day", "day"),
                            ("week", "week"),
                            ("manual", "manual"),
                        ],
                        default="auto",
                        max_length=6,
                    ),
                ),
                ("auto_effective_interval_hours", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("auto_interval_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "queries",
                    models.JSONField(
                        default=list,
                        validators=[newsradar.topics.models.validate_topic_queries],
                    ),
                ),
                (
                    "search_domain_allowlist",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[newsradar.topics.models.validate_domain_filter],
                    ),
                ),
                (
                    "search_language_filter",
                    models.JSONField(
                        blank=True,
                        null=True,
                        validators=[newsradar.topics.models.validate_language_filter],
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics",
                        to="topics.topicgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_fetched_at", "-created_at"],
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        fields=["embedding"],
                        m=16,
                        ef_construction=64,
                        name="topic_embedding_hnsw",
                        opclasses=["vector_l2_ops"],
                    ),
                ],
            },
        ),
    ]
