# Generated by Codex on 2026-05-06

import re

import django.db.models.deletion
from django.db import migrations, models


NORMALIZE_RE = re.compile(r"\s+")


def normalize_name(value):
    return NORMALIZE_RE.sub(" ", str(value or "")).strip()


def topic_name(topic):
    queries = topic.queries or []
    primary_query = queries[0] if queries else ""
    return (
        normalize_name(topic.display_title)
        or normalize_name(primary_query)
        or normalize_name(topic.monitoring_prompt)
        or f"Topic {topic.id}"
    )


def unique_group_name(topic_group_model, user_id, preferred_name):
    base = normalize_name(preferred_name)[:120].strip() or "Untitled collection"
    existing_names = set(
        topic_group_model.objects.filter(user_id=user_id).values_list("name", flat=True)
    )
    if base not in existing_names:
        return base

    index = 2
    while True:
        suffix = f" {index}"
        candidate = f"{base[:120 - len(suffix)].rstrip()}{suffix}"
        if candidate not in existing_names:
            return candidate
        index += 1


def backfill_topic_groups(apps, schema_editor):
    topic_model = apps.get_model("topics", "Topic")
    topic_group_model = apps.get_model("topics", "TopicGroup")

    for topic in topic_model.objects.filter(group__isnull=True).order_by("user_id", "id"):
        group = topic_group_model.objects.create(
            user_id=topic.user_id,
            name=unique_group_name(topic_group_model, topic.user_id, topic_name(topic)),
            description="",
            is_active=True,
        )
        topic.group_id = group.id
        topic.save(update_fields=["group"])


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_purge_legacy_topic_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicgroup",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(backfill_topic_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="topic",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topics",
                to="topics.topicgroup",
            ),
        ),
    ]
