# Generated by Django 5.2.9 on 2026-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0003_topic_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicgroup",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
