# Generated by Django 5.2.9 on 2026-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_group_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='search_recency_filter',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], default='day', max_length=5, null=True),
        ),
    ]
