# Generated by Django 5.2.9 on 2026-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0005_alter_topic_search_recency_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicgroup",
            name="default_search_recency_filter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("year", "year"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="topicgroup",
            name="default_search_language_filter",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicgroup",
            name="default_country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
