# Generated by Django 5.2.9 on 2026-01-20 07:30

import newsradar.topics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_topic_group_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicgroup',
            name='default_search_language_filter',
            field=models.JSONField(blank=True, null=True, validators=[newsradar.topics.models.validate_language_filter]),
        ),
    ]
