# Generated by Django 5.2.9 on 2026-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_topicgroup_default_search_language_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='search_recency_filter',
        ),
        migrations.RemoveField(
            model_name='topicgroup',
            name='default_search_recency_filter',
        ),
        migrations.AddField(
            model_name='topic',
            name='update_frequency',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('manual', 'manual')], default='manual', max_length=6),
        ),
        migrations.AddField(
            model_name='topicgroup',
            name='default_update_frequency',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('manual', 'manual')], max_length=6, null=True),
        ),
    ]
