# Generated by Django 5.2.9 on 2026-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0008_remove_topic_search_recency_filter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="additional_queries_mode",
            field=models.CharField(
                choices=[("auto", "auto"), ("manual", "manual")],
                default="manual",
                max_length=6,
            ),
        ),
    ]
