# Generated by Django 5.2.9 on 2026-02-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0009_topic_additional_queries_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="additional_queries_mode",
            field=models.CharField(
                choices=[("auto", "auto"), ("manual", "manual")],
                default="auto",
                max_length=6,
            ),
        ),
    ]
