# Generated by Django 5.2.9 on 2026-01-06 11:57

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        CreateExtension('vector'),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_domain', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_bucket', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('trend_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='keywords.board')),
                ('content_items', models.ManyToManyField(blank=True, related_name='agenda_items', to='agenda.contentitem')),
            ],
            options={
                'ordering': ['-time_bucket', '-created_at'],
                'unique_together': {('board', 'time_bucket', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ContentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='agenda.contentitem')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-matched_at'],
                'unique_together': {('keyword', 'content_item')},
            },
        ),
        migrations.CreateModel(
            name='KeywordHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_bucket', models.DateField()),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('avg_match_score', models.FloatField(default=0.0)),
                ('recommended_action', models.CharField(choices=[('keep', 'Keep'), ('pause', 'Pause'), ('remove', 'Remove')], default='keep', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-time_bucket'],
                'unique_together': {('keyword', 'time_bucket')},
            },
        ),
        migrations.CreateModel(
            name='KeywordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_text', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('estimated_impact', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_suggestions', to='keywords.board')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('board', 'suggested_text')},
            },
        ),
        migrations.CreateModel(
            name='RawRssEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('rss_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_entries', to='keywords.rsssource')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'unique_together': {('rss_source', 'url')},
            },
        ),
    ]
