# Generated by Django 5.2.9 on 2026-01-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_contentmatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='agenda.contentitem')),
                ('content_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_links', to='agenda.contentsource')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('content_item', 'content_source')},
            },
        ),
    ]
