# Generated by Django 5.2.9 on 2026-01-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_contentsource_contentitemsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitemsource',
            options={},
        ),
    ]
