# Generated by Django 5.2.9 on 2026-01-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_contentitem_origin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitemsource',
            name='order_index',
        ),
    ]
