# Generated by Django 5.2.9 on 2026-01-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_contentitemsource_order_index'),
        ('keywords', '0002_remove_keyword_status_keyword_normalized_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='keywords.keyword'),
        ),
        migrations.DeleteModel(
            name='ContentMatch',
        ),
    ]
